name: 'lockdown repo'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          close-issue: true
          issue-comment: >
            This repository does not accept bug reports.
          skip-closed-issue-comment: true
          close-pr: true
          pr-comment: >
            This repository does not accept pull requests.
          skip-closed-pr-comment: true
